ALTER TABLE events ADD COLUMN IF NOT EXISTS venue_city TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS venue_state TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS venue_latitude DOUBLE PRECISION;
ALTER TABLE events ADD COLUMN IF NOT EXISTS venue_longitude DOUBLE PRECISION;
ALTER TABLE events ADD COLUMN IF NOT EXISTS google_place_id TEXT;
