-- Bridge person-owned relationships to the canonical users table without
-- removing any legacy key. These columns are deliberately nullable during the
-- staged rollout: association with a person is not authentication proof, and
-- ambiguous historical rows must remain usable through their legacy fields.
ALTER TABLE rsvps
  ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE guest_sessions
  ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE guest_invitation_tokens
  ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE message_log
  ADD COLUMN IF NOT EXISTS recipient_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE host_follows
  ADD COLUMN IF NOT EXISTS follower_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE event_photos
  ADD COLUMN IF NOT EXISTS uploader_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;

-- Preserve ambiguous legacy ownership for operator review. This table records
-- the disagreement; it never chooses a winner or changes verification scope.
CREATE TABLE IF NOT EXISTS canonical_user_link_conflicts (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  relationship_type        TEXT NOT NULL,
  source_record_id         BIGINT NOT NULL,
  first_candidate_user_id  INTEGER REFERENCES users(id) ON DELETE SET NULL,
  second_candidate_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  reason                   TEXT NOT NULL,
  detected_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at              TIMESTAMPTZ,
  resolution               TEXT,
  CONSTRAINT canonical_user_link_conflicts_relationship_check
    CHECK (relationship_type IN ('rsvp')),
  CONSTRAINT canonical_user_link_conflicts_reason_check
    CHECK (reason IN ('legacy_owner_mismatch')),
  CONSTRAINT canonical_user_link_conflicts_resolution_check CHECK (
    (resolved_at IS NULL AND resolution IS NULL)
    OR
    (resolved_at IS NOT NULL AND NULLIF(BTRIM(resolution), '') IS NOT NULL)
  ),
  CONSTRAINT canonical_user_link_conflicts_source_uq
    UNIQUE (relationship_type, source_record_id, reason)
);

-- These are exact legacy bridges: every compatibility organizer received the
-- same canonical user in migration 043. No email, phone, or name inference is
-- involved in these updates.
UPDATE guest_sessions session
   SET user_id = organizer.user_id
  FROM organizers organizer
 WHERE organizer.id = session.identity_id
   AND session.user_id IS NULL
   AND organizer.user_id IS NOT NULL;

UPDATE guest_invitation_tokens invitation
   SET user_id = organizer.user_id
  FROM organizers organizer
 WHERE organizer.id = invitation.identity_id
   AND invitation.user_id IS NULL
   AND organizer.user_id IS NOT NULL;

UPDATE host_follows follow
   SET follower_user_id = organizer.user_id
  FROM organizers organizer
 WHERE organizer.id = follow.follower_organizer_id
   AND follow.follower_user_id IS NULL
   AND organizer.user_id IS NOT NULL;

-- An RSVP can have two exact legacy owners. Link it only when one exists or
-- both agree. A disagreement is quarantined while account_id and
-- guest_session_id continue powering the old behavior unchanged.
WITH candidates AS (
  SELECT rsvp.id,
         account.user_id AS account_user_id,
         session.user_id AS session_user_id
    FROM rsvps rsvp
    LEFT JOIN organizers account ON account.id = rsvp.account_id
    LEFT JOIN guest_sessions session ON session.id = rsvp.guest_session_id
)
INSERT INTO canonical_user_link_conflicts (
  relationship_type,
  source_record_id,
  first_candidate_user_id,
  second_candidate_user_id,
  reason
)
SELECT 'rsvp', id, account_user_id, session_user_id, 'legacy_owner_mismatch'
  FROM candidates
 WHERE account_user_id IS NOT NULL
   AND session_user_id IS NOT NULL
   AND account_user_id <> session_user_id
ON CONFLICT DO NOTHING;

WITH candidates AS (
  SELECT rsvp.id,
         account.user_id AS account_user_id,
         session.user_id AS session_user_id
    FROM rsvps rsvp
    LEFT JOIN organizers account ON account.id = rsvp.account_id
    LEFT JOIN guest_sessions session ON session.id = rsvp.guest_session_id
)
UPDATE rsvps rsvp
   SET user_id = COALESCE(candidate.account_user_id, candidate.session_user_id)
  FROM candidates candidate
 WHERE rsvp.id = candidate.id
   AND rsvp.user_id IS NULL
   AND (candidate.account_user_id IS NULL
        OR candidate.session_user_id IS NULL
        OR candidate.account_user_id = candidate.session_user_id);

-- Delivery endpoints remain immutable snapshots, while recipient_user_id lets
-- invitation dedupe survive a person's email change. Only direct owning rows
-- are used; arbitrary recipient-email matches are intentionally excluded.
UPDATE message_log message
   SET recipient_user_id = rsvp.user_id
  FROM rsvps rsvp
 WHERE rsvp.id = message.rsvp_id
   AND message.recipient_user_id IS NULL
   AND rsvp.user_id IS NOT NULL;

UPDATE message_log message
   SET recipient_user_id = invitation.user_id
  FROM guest_invitation_tokens invitation
 WHERE invitation.message_log_id = message.id
   AND message.recipient_user_id IS NULL
   AND invitation.user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS rsvps_event_user_idx
  ON rsvps (event_id, user_id)
  WHERE user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS guest_sessions_user_idx
  ON guest_sessions (user_id, expires_at DESC)
  WHERE user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS guest_invitation_tokens_user_event_idx
  ON guest_invitation_tokens (user_id, target_event_id, id DESC)
  WHERE user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS message_log_recipient_user_idx
  ON message_log (recipient_user_id, created_at DESC)
  WHERE recipient_user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS host_follows_active_follower_user_idx
  ON host_follows (follower_user_id, created_at DESC)
  WHERE follower_user_id IS NOT NULL AND unsubscribed_at IS NULL;

CREATE INDEX IF NOT EXISTS event_photos_uploader_user_idx
  ON event_photos (uploader_user_id, created_at DESC)
  WHERE uploader_user_id IS NOT NULL;

COMMENT ON COLUMN rsvps.user_id IS
  'Canonical attendee association. Authorization still requires account, invitation, or RSVP-token proof.';
COMMENT ON COLUMN guest_sessions.user_id IS
  'Canonical remembered-person association; verified_at and verified_event_id retain proof scope.';
COMMENT ON COLUMN guest_invitation_tokens.user_id IS
  'Canonical intended-recipient association; the bearer token remains the event-scoped authority.';
COMMENT ON COLUMN message_log.recipient_user_id IS
  'Canonical recipient association when known; recipient remains the immutable delivery-address snapshot.';
COMMENT ON COLUMN host_follows.follower_user_id IS
  'Canonical follower. host_organizer_id intentionally remains the followed Host Page/profile.';
COMMENT ON COLUMN event_photos.uploader_user_id IS
  'Canonical uploader when proven by request context; anonymous historical uploads remain NULL.';
