-- Canonical account support controls. The canonical user carries account
-- status; organizers remains the compatible public/profile projection.
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS account_status TEXT NOT NULL DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS suspended_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS suspended_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS suspension_reason TEXT;

ALTER TABLE users DROP CONSTRAINT IF EXISTS users_account_status_check;
ALTER TABLE users ADD CONSTRAINT users_account_status_check
  CHECK (account_status IN ('active', 'suspended'));

ALTER TABLE users DROP CONSTRAINT IF EXISTS users_suspension_state_check;
ALTER TABLE users ADD CONSTRAINT users_suspension_state_check CHECK (
  (account_status = 'active'
    AND suspended_at IS NULL
    AND suspended_by_user_id IS NULL
    AND suspension_reason IS NULL)
  OR
  (account_status = 'suspended'
    AND suspended_at IS NOT NULL
    AND NULLIF(BTRIM(suspension_reason), '') IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS users_account_status_idx
  ON users (account_status, created_at DESC);

-- Every support mutation gets an append-only before/after record. actor_user_id
-- may never be NULL; target_user_id is NULL only for an invitation that has
-- not been claimed yet.
CREATE TABLE IF NOT EXISTS admin_account_audit_log (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id   INTEGER NOT NULL REFERENCES users(id),
  target_user_id  INTEGER REFERENCES users(id),
  action_type     TEXT NOT NULL,
  reason          TEXT NOT NULL,
  before_state    JSONB NOT NULL DEFAULT '{}'::jsonb,
  after_state     JSONB NOT NULL DEFAULT '{}'::jsonb,
  metadata        JSONB NOT NULL DEFAULT '{}'::jsonb,
  request_ip      TEXT,
  user_agent      TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT admin_account_audit_action_check
    CHECK (CHAR_LENGTH(BTRIM(action_type)) BETWEEN 3 AND 80),
  CONSTRAINT admin_account_audit_reason_check
    CHECK (CHAR_LENGTH(BTRIM(reason)) BETWEEN 3 AND 500),
  CONSTRAINT admin_account_audit_ip_check
    CHECK (request_ip IS NULL OR CHAR_LENGTH(request_ip) <= 100),
  CONSTRAINT admin_account_audit_user_agent_check
    CHECK (user_agent IS NULL OR CHAR_LENGTH(user_agent) <= 1000)
);

CREATE INDEX IF NOT EXISTS admin_account_audit_target_idx
  ON admin_account_audit_log (target_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS admin_account_audit_actor_idx
  ON admin_account_audit_log (actor_user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS admin_account_support_notes (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_user_id  INTEGER NOT NULL REFERENCES users(id),
  author_user_id  INTEGER NOT NULL REFERENCES users(id),
  note            TEXT NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT admin_account_support_notes_body_check
    CHECK (CHAR_LENGTH(BTRIM(note)) BETWEEN 2 AND 2000)
);

CREATE INDEX IF NOT EXISTS admin_account_support_notes_target_idx
  ON admin_account_support_notes (target_user_id, created_at DESC);

-- Invitations provision nothing up front. The email becomes a verified login
-- identity only when the recipient consumes the linked magic-link challenge.
CREATE TABLE IF NOT EXISTS admin_account_invitations (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email                TEXT NOT NULL,
  name                 TEXT NOT NULL,
  prepare_host_page    BOOLEAN NOT NULL DEFAULT FALSE,
  magic_link_token_id  INTEGER NOT NULL UNIQUE REFERENCES magic_link_tokens(id),
  created_by_user_id   INTEGER NOT NULL REFERENCES users(id),
  claimed_user_id      INTEGER REFERENCES users(id),
  expires_at           TIMESTAMPTZ NOT NULL,
  claimed_at           TIMESTAMPTZ,
  sent_at              TIMESTAMPTZ,
  revoked_at           TIMESTAMPTZ,
  delivery_failed_at   TIMESTAMPTZ,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT admin_account_invitations_email_check
    CHECK (email = LOWER(BTRIM(email)) AND CHAR_LENGTH(email) BETWEEN 3 AND 320),
  CONSTRAINT admin_account_invitations_name_check
    CHECK (CHAR_LENGTH(BTRIM(name)) BETWEEN 2 AND 160),
  CONSTRAINT admin_account_invitations_expiry_check
    CHECK (expires_at > created_at),
  CONSTRAINT admin_account_invitations_claim_check CHECK (
    (claimed_at IS NULL AND claimed_user_id IS NULL)
    OR
    (claimed_at IS NOT NULL AND claimed_user_id IS NOT NULL AND sent_at IS NOT NULL)
  ),
  CONSTRAINT admin_account_invitations_delivery_check CHECK (
    sent_at IS NULL OR delivery_failed_at IS NULL
  )
);

-- Keep this explicit ALTER for additive safety in environments where an
-- earlier release candidate created the table before delivery state existed.
ALTER TABLE admin_account_invitations
  ADD COLUMN IF NOT EXISTS sent_at TIMESTAMPTZ;

-- A claimed row proves its one-use link was reachable. This backfill lets an
-- environment that briefly ran the pre-sent_at release candidate adopt the
-- stronger claim constraint without losing history or failing migration.
UPDATE admin_account_invitations
   SET sent_at=COALESCE(sent_at,claimed_at,created_at)
 WHERE claimed_at IS NOT NULL AND sent_at IS NULL;

ALTER TABLE admin_account_invitations
  DROP CONSTRAINT IF EXISTS admin_account_invitations_claim_check;
ALTER TABLE admin_account_invitations
  ADD CONSTRAINT admin_account_invitations_claim_check CHECK (
    (claimed_at IS NULL AND claimed_user_id IS NULL)
    OR
    (claimed_at IS NOT NULL AND claimed_user_id IS NOT NULL AND sent_at IS NOT NULL)
  );

ALTER TABLE admin_account_invitations
  DROP CONSTRAINT IF EXISTS admin_account_invitations_delivery_check;
ALTER TABLE admin_account_invitations
  ADD CONSTRAINT admin_account_invitations_delivery_check CHECK (
    sent_at IS NULL OR delivery_failed_at IS NULL
  );

CREATE INDEX IF NOT EXISTS admin_account_invitations_email_idx
  ON admin_account_invitations (email, created_at DESC);
CREATE INDEX IF NOT EXISTS admin_account_invitations_status_idx
  ON admin_account_invitations (created_at DESC)
  WHERE claimed_at IS NULL AND revoked_at IS NULL;

-- Claim links use the existing hashed, single-use magic-link machinery.
ALTER TABLE magic_link_tokens DROP CONSTRAINT IF EXISTS magic_link_tokens_intent_check;
ALTER TABLE magic_link_tokens ADD CONSTRAINT magic_link_tokens_intent_check
  CHECK (intent IN (
    'sign_in', 'follow_host', 'add_photo', 'verify_guest', 'bind_phone',
    'attach_email', 'identity_step_up', 'claim_account'
  ));

-- Audit rows and support notes are intentionally append-only. Corrections are
-- represented by a later row so support history cannot be rewritten.
CREATE OR REPLACE FUNCTION reject_admin_support_history_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION '% is append-only', TG_TABLE_NAME;
END
$$;

DROP TRIGGER IF EXISTS admin_account_audit_immutable ON admin_account_audit_log;
CREATE TRIGGER admin_account_audit_immutable
BEFORE UPDATE OR DELETE ON admin_account_audit_log
FOR EACH ROW EXECUTE FUNCTION reject_admin_support_history_mutation();

DROP TRIGGER IF EXISTS admin_account_support_notes_immutable ON admin_account_support_notes;
CREATE TRIGGER admin_account_support_notes_immutable
BEFORE UPDATE OR DELETE ON admin_account_support_notes
FOR EACH ROW EXECUTE FUNCTION reject_admin_support_history_mutation();

COMMENT ON COLUMN users.account_status IS
  'Canonical access state. Suspension blocks sessions and all account authentication without deleting owned content.';
COMMENT ON TABLE admin_account_audit_log IS
  'Immutable support-action history. Never stores bearer tokens or credential hashes.';
COMMENT ON TABLE admin_account_invitations IS
  'Admin-created account claims. sent_at is authoritative delivery state; no user or verified identity exists until the recipient proves the inbox.';
