-- Admin operators are an independent security principal. They deliberately do
-- not own a canonical user, organizer, event, or any other customer record.
CREATE TABLE IF NOT EXISTS admin_operators (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email                 TEXT NOT NULL UNIQUE,
  role                  TEXT NOT NULL DEFAULT 'support',
  status                TEXT NOT NULL DEFAULT 'active',
  sessions_valid_after  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_login_at         TIMESTAMPTZ,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT admin_operators_email_check CHECK (
    email=LOWER(BTRIM(email)) AND CHAR_LENGTH(email) BETWEEN 3 AND 320
      AND POSITION('@' IN email)>1
  ),
  CONSTRAINT admin_operators_role_check CHECK (role IN ('super_admin','support')),
  CONSTRAINT admin_operators_status_check CHECK (status IN ('active','disabled'))
);

CREATE INDEX IF NOT EXISTS admin_operators_status_idx
  ON admin_operators (status, role, id);

-- Preserve access during the transition, but copy only the normalized email.
-- No user/organizer foreign key or ownership relationship is created.
INSERT INTO admin_operators (email,role,status)
SELECT DISTINCT LOWER(BTRIM(organizer.email)),'super_admin','active'
  FROM organizers organizer
  JOIN users canonical_user ON canonical_user.id=organizer.user_id
 WHERE organizer.is_admin=TRUE
   AND canonical_user.account_status='active'
   AND NULLIF(BTRIM(organizer.email),'') IS NOT NULL
   AND CHAR_LENGTH(LOWER(BTRIM(organizer.email))) BETWEEN 3 AND 320
   AND POSITION('@' IN LOWER(BTRIM(organizer.email)))>1
ON CONFLICT (email) DO NOTHING;

-- Browser-bound six-digit challenges are separate from customer magic links,
-- so an admin code can never create or authenticate a customer account.
CREATE TABLE IF NOT EXISTS admin_auth_challenges (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operator_id     BIGINT NOT NULL REFERENCES admin_operators(id) ON DELETE CASCADE,
  purpose         TEXT NOT NULL,
  action          TEXT,
  target_user_id  INTEGER REFERENCES users(id) ON DELETE CASCADE,
  request_hash    TEXT NOT NULL,
  code_hash       TEXT NOT NULL,
  code_attempts   INTEGER NOT NULL DEFAULT 0,
  expires_at      TIMESTAMPTZ NOT NULL,
  used_at         TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT admin_auth_challenges_purpose_check
    CHECK (purpose IN ('login','step_up')),
  CONSTRAINT admin_auth_challenges_action_check CHECK (
    (purpose='login' AND action IS NULL AND target_user_id IS NULL)
    OR
    (purpose='step_up' AND action='account_delete' AND target_user_id IS NOT NULL)
  ),
  CONSTRAINT admin_auth_challenges_attempts_check
    CHECK (code_attempts BETWEEN 0 AND 5),
  CONSTRAINT admin_auth_challenges_expiry_check
    CHECK (expires_at>created_at)
);

CREATE INDEX IF NOT EXISTS admin_auth_challenges_request_idx
  ON admin_auth_challenges (request_hash, created_at DESC)
  WHERE used_at IS NULL;
CREATE INDEX IF NOT EXISTS admin_auth_challenges_operator_idx
  ON admin_auth_challenges (operator_id, expires_at DESC)
  WHERE used_at IS NULL;

-- A completed step-up yields an opaque one-time proof. The destructive
-- transaction consumes this row with UPDATE ... RETURNING, so rollback also
-- restores the proof and a committed deletion can never reuse it.
CREATE TABLE IF NOT EXISTS admin_action_proofs (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operator_id     BIGINT NOT NULL REFERENCES admin_operators(id) ON DELETE CASCADE,
  action          TEXT NOT NULL CHECK (action IN ('account_delete')),
  target_user_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash      TEXT NOT NULL UNIQUE,
  expires_at      TIMESTAMPTZ NOT NULL,
  consumed_at     TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT admin_action_proofs_expiry_check CHECK (expires_at>created_at)
);

CREATE INDEX IF NOT EXISTS admin_action_proofs_pending_idx
  ON admin_action_proofs (operator_id,action,target_user_id,expires_at DESC)
  WHERE consumed_at IS NULL;

-- Support history can now identify either a transitional customer-admin or an
-- independent operator. Existing rows remain valid and immutable.
ALTER TABLE admin_account_audit_log
  ADD COLUMN IF NOT EXISTS actor_admin_operator_id BIGINT
    REFERENCES admin_operators(id);
ALTER TABLE admin_account_audit_log
  ALTER COLUMN actor_user_id DROP NOT NULL;
ALTER TABLE admin_account_audit_log
  DROP CONSTRAINT IF EXISTS admin_account_audit_actor_check;
ALTER TABLE admin_account_audit_log
  ADD CONSTRAINT admin_account_audit_actor_check
    CHECK (NUM_NONNULLS(actor_user_id,actor_admin_operator_id)=1);
CREATE INDEX IF NOT EXISTS admin_account_audit_operator_idx
  ON admin_account_audit_log (actor_admin_operator_id,created_at DESC);

ALTER TABLE admin_account_support_notes
  ADD COLUMN IF NOT EXISTS author_admin_operator_id BIGINT
    REFERENCES admin_operators(id);
ALTER TABLE admin_account_support_notes
  ALTER COLUMN author_user_id DROP NOT NULL;
ALTER TABLE admin_account_support_notes
  DROP CONSTRAINT IF EXISTS admin_account_support_notes_author_check;
ALTER TABLE admin_account_support_notes
  ADD CONSTRAINT admin_account_support_notes_author_check
    CHECK (NUM_NONNULLS(author_user_id,author_admin_operator_id)=1);

ALTER TABLE admin_account_invitations
  ADD COLUMN IF NOT EXISTS created_by_admin_operator_id BIGINT
    REFERENCES admin_operators(id);
ALTER TABLE admin_account_invitations
  ALTER COLUMN created_by_user_id DROP NOT NULL;
ALTER TABLE admin_account_invitations
  DROP CONSTRAINT IF EXISTS admin_account_invitations_creator_check;
ALTER TABLE admin_account_invitations
  ADD CONSTRAINT admin_account_invitations_creator_check
    CHECK (NUM_NONNULLS(created_by_user_id,created_by_admin_operator_id)=1);

ALTER TABLE host_invitations
  ADD COLUMN IF NOT EXISTS created_by_admin_operator_id BIGINT
    REFERENCES admin_operators(id);

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS suspended_by_admin_operator_id BIGINT
    REFERENCES admin_operators(id),
  ADD COLUMN IF NOT EXISTS deleted_by_admin_operator_id BIGINT
    REFERENCES admin_operators(id);

ALTER TABLE users DROP CONSTRAINT IF EXISTS users_suspension_state_check;
ALTER TABLE users ADD CONSTRAINT users_suspension_state_check CHECK (
  (account_status='active'
    AND suspended_at IS NULL
    AND suspended_by_user_id IS NULL
    AND suspended_by_admin_operator_id IS NULL
    AND suspension_reason IS NULL
    AND deleted_at IS NULL
    AND deleted_by_user_id IS NULL
    AND deleted_by_admin_operator_id IS NULL
    AND deletion_reason IS NULL)
  OR
  (account_status='suspended'
    AND suspended_at IS NOT NULL
    AND NUM_NONNULLS(suspended_by_user_id,suspended_by_admin_operator_id)<=1
    AND NULLIF(BTRIM(suspension_reason),'') IS NOT NULL
    AND deleted_at IS NULL
    AND deleted_by_user_id IS NULL
    AND deleted_by_admin_operator_id IS NULL
    AND deletion_reason IS NULL)
  OR
  (account_status='deleted'
    AND name IS NULL
    AND suspended_at IS NULL
    AND suspended_by_user_id IS NULL
    AND suspended_by_admin_operator_id IS NULL
    AND suspension_reason IS NULL
    AND deleted_at IS NOT NULL
    AND NUM_NONNULLS(deleted_by_user_id,deleted_by_admin_operator_id)<=1
    AND NULLIF(BTRIM(deletion_reason),'') IS NOT NULL)
);

COMMENT ON TABLE admin_operators IS
  'Independent staff identities. Rows have no customer-account or organizer ownership.';
COMMENT ON TABLE admin_action_proofs IS
  'One-time, target/action-bound proof consumed atomically with a destructive admin transaction.';
