-- Admin-team changes use the same one-time proof mechanism as deletion, but
-- bind the proof to one canonical roster target. New operators use their
-- normalized email; existing operators use their immutable numeric ID.
ALTER TABLE admin_auth_challenges
  ADD COLUMN IF NOT EXISTS target_key TEXT;

ALTER TABLE admin_auth_challenges
  DROP CONSTRAINT IF EXISTS admin_auth_challenges_action_check;
ALTER TABLE admin_auth_challenges
  ADD CONSTRAINT admin_auth_challenges_action_check CHECK (
    (purpose='login' AND action IS NULL
      AND target_user_id IS NULL AND target_key IS NULL)
    OR
    (purpose='step_up' AND action='account_delete'
      AND target_user_id IS NOT NULL AND target_key IS NULL)
    OR
    (purpose='step_up' AND action='operator_manage'
      AND target_user_id IS NULL
      AND target_key IS NOT NULL
      AND target_key=LOWER(BTRIM(target_key))
      AND CHAR_LENGTH(target_key) BETWEEN 5 AND 324
      AND (
        target_key ~ '^operator:[1-9][0-9]*$'
        OR target_key ~ '^new:[^[:space:]@]+@[^[:space:]@]+$'
      ))
  );

ALTER TABLE admin_action_proofs
  ADD COLUMN IF NOT EXISTS target_key TEXT,
  ALTER COLUMN target_user_id DROP NOT NULL;

ALTER TABLE admin_action_proofs
  DROP CONSTRAINT IF EXISTS admin_action_proofs_action_check;
ALTER TABLE admin_action_proofs
  DROP CONSTRAINT IF EXISTS admin_action_proofs_target_check;
ALTER TABLE admin_action_proofs
  ADD CONSTRAINT admin_action_proofs_action_check
    CHECK (action IN ('account_delete','operator_manage'));
ALTER TABLE admin_action_proofs
  ADD CONSTRAINT admin_action_proofs_target_check CHECK (
    (action='account_delete' AND target_user_id IS NOT NULL AND target_key IS NULL)
    OR
    (action='operator_manage' AND target_user_id IS NULL
      AND target_key IS NOT NULL
      AND target_key=LOWER(BTRIM(target_key))
      AND CHAR_LENGTH(target_key) BETWEEN 5 AND 324
      AND (
        target_key ~ '^operator:[1-9][0-9]*$'
        OR target_key ~ '^new:[^[:space:]@]+@[^[:space:]@]+$'
      ))
  );

-- A role change is as security-sensitive as a status change. Advancing the
-- credential epoch prevents a demoted (or later re-promoted) operator from
-- retaining an old session, challenge, or action proof.
DROP TRIGGER IF EXISTS admin_operators_invalidate_credentials ON admin_operators;
CREATE TRIGGER admin_operators_invalidate_credentials
BEFORE UPDATE OF status,role ON admin_operators
FOR EACH ROW
WHEN (OLD.status IS DISTINCT FROM NEW.status OR OLD.role IS DISTINCT FROM NEW.role)
EXECUTE FUNCTION invalidate_admin_operator_credentials();

-- Operator history has its own immutable target and actor attribution. Email
-- snapshots keep the record intelligible even if a future migration permits
-- an operator address to change.
CREATE TABLE IF NOT EXISTS admin_operator_audit_log (
  id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_admin_operator_id   BIGINT NOT NULL REFERENCES admin_operators(id),
  target_admin_operator_id  BIGINT NOT NULL REFERENCES admin_operators(id),
  actor_email               TEXT NOT NULL,
  target_email              TEXT NOT NULL,
  action_type               TEXT NOT NULL,
  reason                    TEXT NOT NULL,
  before_state              JSONB NOT NULL DEFAULT '{}'::jsonb,
  after_state               JSONB NOT NULL DEFAULT '{}'::jsonb,
  request_ip                TEXT,
  user_agent                TEXT,
  created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT admin_operator_audit_action_check
    CHECK (CHAR_LENGTH(BTRIM(action_type)) BETWEEN 3 AND 80),
  CONSTRAINT admin_operator_audit_reason_check
    CHECK (CHAR_LENGTH(BTRIM(reason)) BETWEEN 8 AND 500),
  CONSTRAINT admin_operator_audit_actor_email_check
    CHECK (actor_email=LOWER(BTRIM(actor_email)) AND CHAR_LENGTH(actor_email)<=320),
  CONSTRAINT admin_operator_audit_target_email_check
    CHECK (target_email=LOWER(BTRIM(target_email)) AND CHAR_LENGTH(target_email)<=320),
  CONSTRAINT admin_operator_audit_ip_check
    CHECK (request_ip IS NULL OR CHAR_LENGTH(request_ip)<=100),
  CONSTRAINT admin_operator_audit_user_agent_check
    CHECK (user_agent IS NULL OR CHAR_LENGTH(user_agent)<=1000)
);

CREATE INDEX IF NOT EXISTS admin_operator_audit_target_idx
  ON admin_operator_audit_log (target_admin_operator_id,created_at DESC);
CREATE INDEX IF NOT EXISTS admin_operator_audit_actor_idx
  ON admin_operator_audit_log (actor_admin_operator_id,created_at DESC);

DROP TRIGGER IF EXISTS admin_operator_audit_immutable ON admin_operator_audit_log;
CREATE TRIGGER admin_operator_audit_immutable
BEFORE UPDATE OR DELETE ON admin_operator_audit_log
FOR EACH ROW EXECUTE FUNCTION reject_admin_support_history_mutation();

-- Roster records are disabled, never deleted. Keeping the principal row makes
-- every historic actor/target reference permanent and human-auditable.
CREATE OR REPLACE FUNCTION reject_admin_operator_deletion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'admin_operators is retained for immutable audit attribution';
END
$$;

DROP TRIGGER IF EXISTS admin_operators_no_delete ON admin_operators;
CREATE TRIGGER admin_operators_no_delete
BEFORE DELETE ON admin_operators
FOR EACH ROW EXECUTE FUNCTION reject_admin_operator_deletion();

COMMENT ON COLUMN admin_auth_challenges.target_key IS
  'Canonical operator-management target: operator:<id> or new:<normalized_email>.';
COMMENT ON COLUMN admin_action_proofs.target_key IS
  'Exact canonical target bound to an operator_manage proof.';
COMMENT ON TABLE admin_operator_audit_log IS
  'Immutable operator-roster history with stable actor and target attribution.';
