-- Administrators may prepare an account contact change, but the recipient is
-- the only party allowed to turn it into a verified sign-in identity. Email
-- requests use a hashed one-time link; phone requests use Twilio Verify. Raw
-- bearer tokens and verification codes are never persisted.
CREATE TABLE IF NOT EXISTS admin_account_identity_change_requests (
  id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_user_id                  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  identity_type                   TEXT NOT NULL,
  value                           TEXT NOT NULL,
  normalized_value                TEXT NOT NULL,
  status                          TEXT NOT NULL DEFAULT 'pending',
  request_token_hash              TEXT,
  provider_sid                    TEXT,
  verification_attempts           INTEGER NOT NULL DEFAULT 0,
  requested_by_user_id            INTEGER REFERENCES users(id),
  requested_by_admin_operator_id  BIGINT REFERENCES admin_operators(id),
  reason                          TEXT NOT NULL,
  sent_at                         TIMESTAMPTZ,
  expires_at                      TIMESTAMPTZ NOT NULL,
  verified_at                     TIMESTAMPTZ,
  cancelled_at                    TIMESTAMPTZ,
  expired_at                      TIMESTAMPTZ,
  delivery_failed_at              TIMESTAMPTZ,
  conflict_at                     TIMESTAMPTZ,
  created_at                      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT admin_identity_change_type_check
    CHECK (identity_type IN ('email','phone')),
  CONSTRAINT admin_identity_change_value_check
    CHECK (CHAR_LENGTH(BTRIM(value)) BETWEEN 3 AND 320),
  CONSTRAINT admin_identity_change_normalized_check CHECK (
    (identity_type='email'
      AND normalized_value=LOWER(BTRIM(value))
      AND CHAR_LENGTH(normalized_value) BETWEEN 3 AND 320)
    OR
    (identity_type='phone'
      AND value=normalized_value
      AND normalized_value ~ '^\+[1-9][0-9]{7,14}$')
  ),
  CONSTRAINT admin_identity_change_status_check
    CHECK (status IN ('pending','verified','cancelled','expired','delivery_failed','conflict')),
  CONSTRAINT admin_identity_change_actor_check
    CHECK (NUM_NONNULLS(requested_by_user_id,requested_by_admin_operator_id)=1),
  CONSTRAINT admin_identity_change_reason_check
    CHECK (CHAR_LENGTH(BTRIM(reason)) BETWEEN 8 AND 500),
  CONSTRAINT admin_identity_change_attempts_check
    CHECK (verification_attempts BETWEEN 0 AND 5),
  CONSTRAINT admin_identity_change_delivery_method_check CHECK (
    (identity_type='email' AND provider_sid IS NULL)
    OR
    (identity_type='phone')
  ),
  CONSTRAINT admin_identity_change_sent_proof_check CHECK (
    sent_at IS NULL
    OR (request_token_hash IS NOT NULL
      AND (identity_type='email' OR provider_sid IS NOT NULL))
  ),
  CONSTRAINT admin_identity_change_terminal_state_check CHECK (
    (status='pending'
      AND verified_at IS NULL AND cancelled_at IS NULL
      AND expired_at IS NULL AND delivery_failed_at IS NULL AND conflict_at IS NULL)
    OR
    (status='verified'
      AND verified_at IS NOT NULL AND cancelled_at IS NULL
      AND expired_at IS NULL AND delivery_failed_at IS NULL AND conflict_at IS NULL)
    OR
    (status='cancelled'
      AND verified_at IS NULL AND cancelled_at IS NOT NULL
      AND expired_at IS NULL AND delivery_failed_at IS NULL AND conflict_at IS NULL)
    OR
    (status='expired'
      AND verified_at IS NULL AND cancelled_at IS NULL
      AND expired_at IS NOT NULL AND delivery_failed_at IS NULL AND conflict_at IS NULL)
    OR
    (status='delivery_failed'
      AND verified_at IS NULL AND cancelled_at IS NULL
      AND expired_at IS NULL AND delivery_failed_at IS NOT NULL AND conflict_at IS NULL)
    OR
    (status='conflict'
      AND verified_at IS NULL AND cancelled_at IS NULL
      AND expired_at IS NULL AND delivery_failed_at IS NULL AND conflict_at IS NOT NULL)
  ),
  CONSTRAINT admin_identity_change_expiry_check
    CHECK (expires_at>created_at)
);

CREATE UNIQUE INDEX IF NOT EXISTS admin_identity_change_token_uq
  ON admin_account_identity_change_requests (request_token_hash)
  WHERE request_token_hash IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS admin_identity_change_pending_target_type_uq
  ON admin_account_identity_change_requests (target_user_id,identity_type)
  WHERE status='pending';

CREATE UNIQUE INDEX IF NOT EXISTS admin_identity_change_pending_value_uq
  ON admin_account_identity_change_requests (identity_type,normalized_value)
  WHERE status='pending';

CREATE INDEX IF NOT EXISTS admin_identity_change_target_idx
  ON admin_account_identity_change_requests (target_user_id,created_at DESC);

CREATE INDEX IF NOT EXISTS admin_identity_change_pending_phone_idx
  ON admin_account_identity_change_requests (normalized_value,expires_at DESC)
  WHERE identity_type='phone' AND status='pending';

COMMENT ON TABLE admin_account_identity_change_requests IS
  'Admin-prepared contact changes that become sign-in identities only after recipient-controlled verification.';
COMMENT ON COLUMN admin_account_identity_change_requests.request_token_hash IS
  'SHA-256 hash of the recipient link token. The raw token is delivered only to the proposed email or phone.';
COMMENT ON COLUMN admin_account_identity_change_requests.provider_sid IS
  'Twilio Verify SID for a pending phone proof; never a verification code.';
