-- Done For You records mark accounts that staff prepared on a client's
-- behalf. The canonical user remains the owner; the marker deliberately
-- duplicates no contact or profile data.
CREATE TABLE IF NOT EXISTS admin_done_for_you_clients (
  id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_user_id                INTEGER NOT NULL UNIQUE REFERENCES users(id),
  created_by_admin_operator_id  BIGINT NOT NULL REFERENCES admin_operators(id),
  created_at                    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS admin_done_for_you_clients_created_by_idx
  ON admin_done_for_you_clients (created_by_admin_operator_id,created_at DESC);

-- New claim invitations can be bound to the already-provisioned owner. NULL
-- preserves every legacy invitation, which continues to create/resolve its
-- owner only after recipient proof.
ALTER TABLE admin_account_invitations
  ADD COLUMN IF NOT EXISTS target_user_id INTEGER REFERENCES users(id);

ALTER TABLE admin_account_invitations
  DROP CONSTRAINT IF EXISTS admin_account_invitations_target_claim_check;
ALTER TABLE admin_account_invitations
  ADD CONSTRAINT admin_account_invitations_target_claim_check CHECK (
    claimed_user_id IS NULL
    OR target_user_id IS NULL
    OR claimed_user_id=target_user_id
  );

CREATE INDEX IF NOT EXISTS admin_account_invitations_target_idx
  ON admin_account_invitations (target_user_id,created_at DESC)
  WHERE target_user_id IS NOT NULL;

-- expires_at cannot appear in an immutable partial-index predicate. Claim
-- creation must revoke an expired/stale row before inserting its replacement.
CREATE UNIQUE INDEX IF NOT EXISTS admin_account_invitations_pending_target_uq
  ON admin_account_invitations (target_user_id)
  WHERE target_user_id IS NOT NULL
    AND claimed_at IS NULL
    AND revoked_at IS NULL
    AND delivery_failed_at IS NULL;

CREATE OR REPLACE FUNCTION reject_admin_invitation_target_reassignment()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.target_user_id IS DISTINCT FROM NEW.target_user_id THEN
    RAISE EXCEPTION 'account invitation target is immutable';
  END IF;
  RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS admin_account_invitation_target_immutable
  ON admin_account_invitations;
CREATE TRIGGER admin_account_invitation_target_immutable
BEFORE UPDATE OF target_user_id ON admin_account_invitations
FOR EACH ROW EXECUTE FUNCTION reject_admin_invitation_target_reassignment();

COMMENT ON TABLE admin_done_for_you_clients IS
  'PII-free marker for a canonical account and Host Page prepared by an independent administrator.';
COMMENT ON COLUMN admin_account_invitations.target_user_id IS
  'Optional pre-provisioned owner. A successful claim must resolve to this same canonical user.';
