-- A Done For You editor workspace is a short-lived, operator-bound grant.
-- It never authenticates as the customer and never changes event ownership.
CREATE TABLE IF NOT EXISTS admin_event_editor_workspaces (
  id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash                  TEXT NOT NULL UNIQUE,
  done_for_you_client_id      BIGINT NOT NULL
    REFERENCES admin_done_for_you_clients(id) ON DELETE CASCADE,
  actor_admin_operator_id     BIGINT NOT NULL REFERENCES admin_operators(id),
  target_user_id              INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  organizer_id                INTEGER NOT NULL REFERENCES organizers(id) ON DELETE CASCADE,
  event_id                    INTEGER REFERENCES events(id) ON DELETE CASCADE,
  status                      TEXT NOT NULL DEFAULT 'active',
  expires_at                  TIMESTAMPTZ NOT NULL,
  closed_at                   TIMESTAMPTZ,
  created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT admin_event_editor_workspaces_token_check
    CHECK (token_hash ~ '^[a-f0-9]{64}$'),
  CONSTRAINT admin_event_editor_workspaces_status_check
    CHECK (status IN ('active','completed','exited','revoked','expired')),
  CONSTRAINT admin_event_editor_workspaces_expiry_check
    CHECK (expires_at>created_at),
  CONSTRAINT admin_event_editor_workspaces_lifecycle_check CHECK (
    (status='active' AND closed_at IS NULL)
    OR
    (status<>'active' AND closed_at IS NOT NULL)
  )
);

-- One active workspace per operator keeps browser context unambiguous. A
-- bound draft can likewise be edited by only one operator at a time.
CREATE UNIQUE INDEX IF NOT EXISTS admin_event_editor_workspaces_actor_active_uq
  ON admin_event_editor_workspaces (actor_admin_operator_id)
  WHERE status='active';
CREATE UNIQUE INDEX IF NOT EXISTS admin_event_editor_workspaces_event_active_uq
  ON admin_event_editor_workspaces (event_id)
  WHERE status='active' AND event_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS admin_event_editor_workspaces_client_idx
  ON admin_event_editor_workspaces (done_for_you_client_id,created_at DESC);

-- Tokens and ownership scope are immutable. Stage 2 may bind an unbound
-- workspace to its newly-created draft exactly once, but may never retarget it.
CREATE OR REPLACE FUNCTION reject_admin_editor_workspace_reassignment()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.token_hash IS DISTINCT FROM NEW.token_hash
     OR OLD.done_for_you_client_id IS DISTINCT FROM NEW.done_for_you_client_id
     OR OLD.actor_admin_operator_id IS DISTINCT FROM NEW.actor_admin_operator_id
     OR OLD.target_user_id IS DISTINCT FROM NEW.target_user_id
     OR OLD.organizer_id IS DISTINCT FROM NEW.organizer_id
     OR (OLD.event_id IS NOT NULL AND OLD.event_id IS DISTINCT FROM NEW.event_id) THEN
    RAISE EXCEPTION 'admin event editor workspace scope is immutable';
  END IF;
  RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS admin_event_editor_workspace_scope_immutable
  ON admin_event_editor_workspaces;
CREATE TRIGGER admin_event_editor_workspace_scope_immutable
BEFORE UPDATE OF token_hash,done_for_you_client_id,actor_admin_operator_id,target_user_id,organizer_id,event_id
ON admin_event_editor_workspaces
FOR EACH ROW EXECUTE FUNCTION reject_admin_editor_workspace_reassignment();

-- Keep direct SQL/support tooling fail-closed too. Supported application paths
-- revoke and audit the rows before advancing this credential epoch, so this
-- trigger is normally a zero-row safety net and never invents an audit actor.
CREATE OR REPLACE FUNCTION revoke_admin_editor_workspaces_on_operator_access_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE admin_event_editor_workspaces
     SET status='revoked',closed_at=clock_timestamp()
   WHERE actor_admin_operator_id=NEW.id
     AND status='active';
  RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS admin_operator_access_change_revokes_editor_workspaces
  ON admin_operators;
CREATE TRIGGER admin_operator_access_change_revokes_editor_workspaces
AFTER UPDATE OF status,role,sessions_valid_after ON admin_operators
FOR EACH ROW
WHEN (
  OLD.status IS DISTINCT FROM NEW.status
  OR OLD.role IS DISTINCT FROM NEW.role
  OR OLD.sessions_valid_after IS DISTINCT FROM NEW.sessions_valid_after
)
EXECUTE FUNCTION revoke_admin_editor_workspaces_on_operator_access_change();

COMMENT ON TABLE admin_event_editor_workspaces IS
  'Short-lived independent-admin grants for one Done For You Host Page and, optionally, one draft event. Never a customer session.';
