-- The public flyer intake is deliberately separate from permanent accounts and
-- events. A submission becomes a Done For You client and draft only after an
-- administrator reviews it. The singleton switch lets the Super Admin pause
-- the pilot without removing or rebuilding the intake page.
CREATE TABLE IF NOT EXISTS admin_flyer_intake_settings (
  singleton                    BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
  accepting_submissions        BOOLEAN NOT NULL DEFAULT FALSE,
  updated_by_admin_operator_id BIGINT REFERENCES admin_operators(id),
  updated_at                   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO admin_flyer_intake_settings (singleton,accepting_submissions)
VALUES (TRUE,FALSE)
ON CONFLICT (singleton) DO NOTHING;

CREATE TABLE IF NOT EXISTS admin_flyer_requests (
  id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submitter_name                TEXT NOT NULL,
  host_name                     TEXT NOT NULL,
  email                         TEXT NOT NULL,
  phone_e164                    TEXT NOT NULL,
  artwork_credit                TEXT,
  flyer_url                     TEXT NOT NULL,
  flyer_public_id               TEXT NOT NULL,
  flyer_accent_color            TEXT,
  sms_consent_at                TIMESTAMPTZ NOT NULL,
  sms_consent_version           TEXT NOT NULL,
  status                        TEXT NOT NULL DEFAULT 'submitted',
  done_for_you_client_id        BIGINT REFERENCES admin_done_for_you_clients(id),
  event_id                      INTEGER REFERENCES events(id),
  assigned_admin_operator_id    BIGINT REFERENCES admin_operators(id),
  started_at                    TIMESTAMPTZ,
  ready_for_review_at           TIMESTAMPTZ,
  preview_sent_at               TIMESTAMPTZ,
  changes_requested_at          TIMESTAMPTZ,
  promoter_approved_at          TIMESTAMPTZ,
  phone_verified_at             TIMESTAMPTZ,
  claimed_at                    TIMESTAMPTZ,
  published_at                  TIMESTAMPTZ,
  rejected_at                   TIMESTAMPTZ,
  latest_fix_request            TEXT,
  preview_revision              INTEGER NOT NULL DEFAULT 1,
  preview_token_hash            TEXT,
  preview_token_expires_at      TIMESTAMPTZ,
  created_at                    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT admin_flyer_requests_name_check
    CHECK (CHAR_LENGTH(BTRIM(submitter_name)) BETWEEN 1 AND 160),
  CONSTRAINT admin_flyer_requests_host_check
    CHECK (CHAR_LENGTH(BTRIM(host_name)) BETWEEN 1 AND 100),
  CONSTRAINT admin_flyer_requests_email_check
    CHECK (email=LOWER(BTRIM(email)) AND CHAR_LENGTH(email)<=320),
  CONSTRAINT admin_flyer_requests_phone_check
    CHECK (phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  CONSTRAINT admin_flyer_requests_artwork_check
    CHECK (artwork_credit IS NULL OR CHAR_LENGTH(artwork_credit)<=160),
  CONSTRAINT admin_flyer_requests_url_check
    CHECK (flyer_url ~ '^https://'),
  CONSTRAINT admin_flyer_requests_public_id_check
    CHECK (CHAR_LENGTH(flyer_public_id) BETWEEN 1 AND 500),
  CONSTRAINT admin_flyer_requests_accent_check
    CHECK (flyer_accent_color IS NULL OR flyer_accent_color ~ '^#[0-9A-Fa-f]{6}$'),
  CONSTRAINT admin_flyer_requests_status_check
    CHECK (status IN (
      'submitted','building','ready_for_review','preview_sent',
      'changes_requested','promoter_approved','published','rejected'
    )),
  CONSTRAINT admin_flyer_requests_revision_check CHECK (preview_revision>0),
  CONSTRAINT admin_flyer_requests_preview_token_check
    CHECK (
      (preview_token_hash IS NULL AND preview_token_expires_at IS NULL)
      OR
      (preview_token_hash ~ '^[a-f0-9]{64}$' AND preview_token_expires_at IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS admin_flyer_requests_queue_idx
  ON admin_flyer_requests (status,created_at DESC);
CREATE INDEX IF NOT EXISTS admin_flyer_requests_phone_idx
  ON admin_flyer_requests (phone_e164,created_at DESC);
CREATE INDEX IF NOT EXISTS admin_flyer_requests_client_idx
  ON admin_flyer_requests (done_for_you_client_id,created_at DESC)
  WHERE done_for_you_client_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS admin_flyer_requests_event_idx
  ON admin_flyer_requests (event_id)
  WHERE event_id IS NOT NULL;

-- Each lifecycle text has an explicit, durable delivery attempt. The revision
-- key makes preview retries idempotent while still allowing an approved revised
-- preview later. Submission itself never creates a confirmation text.
CREATE TABLE IF NOT EXISTS admin_flyer_request_messages (
  id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flyer_request_id           BIGINT NOT NULL REFERENCES admin_flyer_requests(id) ON DELETE CASCADE,
  message_kind               TEXT NOT NULL CHECK (message_kind IN ('preview','live')),
  revision                   INTEGER NOT NULL DEFAULT 1 CHECK (revision>0),
  recipient                  TEXT NOT NULL CHECK (recipient ~ '^\+[1-9][0-9]{7,14}$'),
  status                     TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sending','sent','failed')),
  provider_id                TEXT,
  error                      TEXT,
  initiated_by_admin_operator_id BIGINT NOT NULL REFERENCES admin_operators(id),
  created_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sent_at                    TIMESTAMPTZ,
  UNIQUE (flyer_request_id,message_kind,revision)
);

CREATE INDEX IF NOT EXISTS admin_flyer_request_messages_request_idx
  ON admin_flyer_request_messages (flyer_request_id,created_at DESC);

COMMENT ON TABLE admin_flyer_requests IS
  'Human-reviewed SMS-first flyer submissions; no account or event is created by public intake.';
COMMENT ON COLUMN admin_flyer_requests.sms_consent_at IS
  'Consent to receive transactional preview, verification, and publication texts for this submission only.';
COMMENT ON TABLE admin_flyer_request_messages IS
  'Idempotent delivery ledger for manually approved Done For You preview and live SMS messages.';
