-- A preview recipient proves only that they control the mobile number attached
-- to one reviewed flyer request. This deliberately does not create a session,
-- verify a canonical account identity, or grant access to any other event.
CREATE TABLE IF NOT EXISTS admin_flyer_request_phone_challenges (
  id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flyer_request_id           BIGINT NOT NULL REFERENCES admin_flyer_requests(id) ON DELETE CASCADE,
  preview_revision           INTEGER NOT NULL CHECK (preview_revision>0),
  provider_sid               TEXT NOT NULL,
  phone_e164                 TEXT NOT NULL,
  verification_attempts      INTEGER NOT NULL DEFAULT 0,
  expires_at                 TIMESTAMPTZ NOT NULL,
  verified_at                TIMESTAMPTZ,
  superseded_at              TIMESTAMPTZ,
  created_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT admin_flyer_phone_challenge_sid_check
    CHECK (provider_sid ~ '^VE[0-9A-Fa-f]{32}$'),
  CONSTRAINT admin_flyer_phone_challenge_phone_check
    CHECK (phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  CONSTRAINT admin_flyer_phone_challenge_attempts_check
    CHECK (verification_attempts BETWEEN 0 AND 5),
  CONSTRAINT admin_flyer_phone_challenge_expiry_check
    CHECK (expires_at>created_at),
  CONSTRAINT admin_flyer_phone_challenge_state_check
    CHECK (verified_at IS NULL OR superseded_at IS NULL)
);

CREATE UNIQUE INDEX IF NOT EXISTS admin_flyer_phone_challenge_active_uq
  ON admin_flyer_request_phone_challenges (flyer_request_id)
  WHERE verified_at IS NULL AND superseded_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_flyer_phone_challenge_request_idx
  ON admin_flyer_request_phone_challenges (flyer_request_id,created_at DESC);

COMMENT ON TABLE admin_flyer_request_phone_challenges IS
  'Request-scoped Twilio Verify proofs for promoter approval; never an account authentication credential.';
