-- Operational Done For You notices are committed with the request state that
-- caused them. Each active Super Admin receives a separate durable delivery;
-- the stable provider key makes a retry safe even if Resend accepted the email
-- before the worker could record its response.
CREATE TABLE IF NOT EXISTS admin_flyer_request_notifications (
  id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flyer_request_id            BIGINT NOT NULL
                                REFERENCES admin_flyer_requests(id) ON DELETE CASCADE,
  notification_kind           TEXT NOT NULL
                                CHECK (notification_kind IN ('submitted','approved')),
  recipient_admin_operator_id BIGINT
                                REFERENCES admin_operators(id) ON DELETE SET NULL,
  recipient                   TEXT NOT NULL,
  idempotency_key             TEXT NOT NULL UNIQUE,
  status                      TEXT NOT NULL DEFAULT 'pending'
                                CHECK (status IN ('pending','sending','sent','failed','skipped')),
  attempt_count               INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count>=0),
  last_attempt_at             TIMESTAMPTZ,
  next_attempt_at             TIMESTAMPTZ,
  provider_id                 TEXT,
  error                       TEXT,
  created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sent_at                     TIMESTAMPTZ,
  CONSTRAINT admin_flyer_request_notifications_recipient_check
    CHECK (recipient=LOWER(BTRIM(recipient)) AND CHAR_LENGTH(recipient) BETWEEN 3 AND 320),
  CONSTRAINT admin_flyer_request_notifications_key_check
    CHECK (CHAR_LENGTH(idempotency_key) BETWEEN 1 AND 200),
  UNIQUE (flyer_request_id,notification_kind,recipient)
);

CREATE INDEX IF NOT EXISTS admin_flyer_request_notifications_due_idx
  ON admin_flyer_request_notifications (next_attempt_at,id)
  WHERE status IN ('pending','failed');

CREATE INDEX IF NOT EXISTS admin_flyer_request_notifications_lease_idx
  ON admin_flyer_request_notifications (last_attempt_at,id)
  WHERE status='sending';

COMMENT ON TABLE admin_flyer_request_notifications IS
  'Per-Super-Admin durable email outbox for new and promoter-approved Done For You flyers.';
